# Generated by Django 5.1.2 on 2024-10-17 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sage_invoice", "0003_alter_item_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="invoice",
            field=models.OneToOneField(
                db_comment="Reference to the associated invoice",
                help_text="The invoice associated with this total.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expense",
                to="sage_invoice.invoice",
                verbose_name="Invoice",
            ),
        ),
    ]
