name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage codecov pytest
        pip install -r packages/requirements-dev.txt
    - name: Run tests
      run: |
        coverage run -m pytest
    - name: Generate coverage report
      run: coverage xml
    - name: Run Tox tests
      run: tox
    - name: Run pre-commmit hooks
      run: tox -e pre-commit
    - name: Upload coverage to Codecov
      run: codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}